### ISSUE TITLE
sso.getProfile only returns profile

### ISSUE THREAD

**Issue by thayallans** [workos-inc/workos-node#355]
WorkOS Docs say that `sso.getProfile` should return an access_token and the Profile but the SDK only returns Profile. ([https://workos.com/docs/reference/sso/profile/get](https://workos.com/docs/reference/sso/profile/get))

**Comment by maxdeviant** [comment]
Hi @thayallans, you are correct that we should be exposing the `access_token` here.

We'll look to get this change made soon.

**Comment by maxdeviant** [comment]
This is addressed as part of #385 and will be part of the `v1.0.0` release, which will be coming along shortly.

**Comment by maxdeviant** [comment]
@thayallans This is fixed in [`v1.0.0`](https://github.com/workos-inc/workos-node/releases/tag/v1.0.0).
