### ISSUE TITLE
Interface for `CreatePasswordlessSession` has a type issue

### ISSUE THREAD

**Issue by Emsu** [workos-inc/workos-node#373]
```
export interface CreatePasswordlessSessionOptions {
  email: string;
  redirectURI?: string;
  state?: string;
  type: 'MagicLink';
}
```

`type` can't equal 'MagicLink' as `CreatePasswordlessSessionOptions` is an interface and can't have concrete values. It's causing type issues when trying to use it in Typescript. `type` should equal `string`

**Comment by Emsu** [comment]
Error is:
```
Argument of type '{ email: string; type: string; }' is not assignable to parameter of type 'CreatePasswordlessSessionOptions'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type '"MagicLink"'.ts(2345)
```
Typescript v4.2.3

I think the thing is that the type field needs to be a type and not "MagicLink". You can't set a default value in an interface.
So the code in my initial report should look like the following:
```
export interface CreatePasswordlessSessionOptions {
  email: string;
  redirectURI?: string;
  state?: string;
  type: string; // <-- this is the change
}
```

Where "MagicLink" is changed to the type `string` or maybe a URL type. Because "MagicLink" is a string value, not an actual type. This code is an interface so instead of putting a default value, my understanding is that you need to put an actual type.

@marktran Let me know how I can help.

**Comment by maxdeviant** [comment]
Hey @Emsu, the type `'MagicLink'` is a valid [string literal](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-types) type that constrains the set of possible values to just `'MagicLink'`.

Judging by the error you provided, it looks like you have a type `{ email: string; type: string; }` in your code that you are trying to pass as the argument to `createSession`, is that right?

If you change it to something like this the error should go away:

```ts
const { email } = // ... pull the email from somewhere

const session = await workos.passwordless.createSession({
  email,
  type: 'MagicLink'
});
```

**Comment by Emsu** [comment]
Hmm, well if that's the case, I'm not sure why Typescript is flagging an issue. Here's the code. It looks basically the same as what you have written:

```
    const { email } = createMagicLinkDto;

    const session_options = {
      email,
      type: 'MagicLink',
    };

    // @ts-ignore
    const session = await workos.passwordless.createSession(session_options);
    await workos.passwordless.sendSession(session.id);
```

The line below where I have ts-ignore is where the error is being flagged. Based on what you're saying, then the TS issue shouldn't be showing up?

**Comment by Emsu** [comment]
@maxdeviant Ah ok I tried both ways and I see that if I put the object in directly it doesn't have issues. Both my sample and your sample came from the docs though albeit from different areas.

Here's a repro combining both code samples from the docs. Your specific example doesn't break. The second example in the doc breaks where session_options is constructed separately.
```
    const { email } = createMagicLinkDto;

    const session_options = {
      email,
      type: 'MagicLink',
    };

    const session1 = await workos.passwordless.createSession({
      email,
      type: 'MagicLink'
    }); // <--- no issues

    const session2 = await workos.passwordless.createSession(session_options); // <--- TS issue here
    await workos.passwordless.sendSession(session.id); // Does this send the email?
```

**Comment by maxdeviant** [comment]
Ah, looks like an issue with our example in the docs. The issue is that when declaring the options without a type signature it incorrectly infers `type: 'MagicLink` to be `type: string`.

Using `as const` does correct the issue:

```ts
const sessionOptions = {
  email,
  type: 'MagicLink'
} as const;

await workos.passwordless.createSession(sessionOptions);
```

as does adding a type annotation:

```ts
const sessionOptions: CreatePasswordlessSessionOptions = {
  email,
  type: 'MagicLink'
};

await workos.passwordless.createSession(sessionOptions);
```

But the recommended usage here should be to just pass the options as an object literal as I showed above, as this will provide the best type inference/intellisense.

We'll update our docs accordingly. Sorry you ran into this issue!

**Comment by maxdeviant** [comment]
@Emsu We've updated our docs to show the correct usage here.

Do let us know if you find any other issues are you're working through your integration 🙂
