### ISSUE TITLE
The `Exception` classes don't inherit from `Error`

### ISSUE THREAD

**Issue by TooTallNate** [workos-inc/workos-node#380]
Even though the TypeScript types [_looks like_](https://github.com/workos-inc/workos-node/blob/master/src/common/interfaces/http-exception.interface.ts#L1) they extends from `Error`, in reality the Exception classes are using [`implements` instead of `extends`](https://github.com/workos-inc/workos-node/blob/master/src/common/exceptions/generic-server.exception.ts#L3), which makes the compiled output not inherit from `Error`.

This caused an issue in our codebase where we were testing for `err instanceof Error` which is currently not working as expected.

**Comment by rohanjadvani** [comment]
@TooTallNate - Thanks for mentioning this! We have pushed out a fix in our [latest release](https://www.npmjs.com/package/@workos-inc/node/v/0.10.3). Please let us know if you come across any further issues. 🙂

**Comment by TooTallNate** [comment]
Thanks for the quick fix!
