### ISSUE TITLE
organization method does not exports get and delete function

### ISSUE THREAD

**Issue by tugzera** [workos-inc/workos-node#403]
import WorkOS from '@workos-inc/node';

export const workOs = new WorkOS('sk_some_valid_key');

workOs.organizations -> only display create / list / update method

**Comment by maxdeviant** [comment]
Hey @tugzera!

`getOrganization` and `deleteOrganization` were added in [v1.1.0](https://github.com/workos-inc/workos-node/releases/tag/v1.1.0).

What version of the SDK are you currently using?

**Comment by tugzera** [comment]
Thx!!! I was using 1.0.0... updating now
