### ISSUE TITLE
Export ProfileAndToken interface

### ISSUE THREAD

**Issue by edyrkaj** [workos-inc/workos-node#421]
**Description:**
For the sso option as you have other exported members you need to add the export for type ProfileAndToken

```
export * from './authorization-url-options.interface';
export * from './connection-type.enum';
export * from './connection.interface';
export * from './get-profile-and-token-options.interface';
export * from './profile.interface';
```
Needs to add only this line:
`export * from './profile-and-token.interface';`

Thnx

**Comment by maxdeviant** [comment]
Hi @edyrkaj!

`ProfileAndToken` is now exported in `v1.4.0`.
